#!/bin/bash

git filter-branch --commit-filter '
        if [ "$GIT_COMMITTER_NAME" = "<root>" ];
        then
                GIT_COMMITTER_NAME="<RTOSkit>";
                GIT_AUTHOR_NAME="<RTOSkit>";
                GIT_COMMITTER_EMAIL="<rtoskit@gmail.com>";
                GIT_AUTHOR_EMAIL="<rtoskit@gmail.com>";
                git commit-tree "$@";
        else
                git commit-tree "$@";
        fi' HEAD
